---
# Default variables to auto-configuration of reverse proxy for federations
instances: []
# variables to control whether to configure one instance and/or a specific stanza at a time or everything from the configurations
inst_name: "{{ item.0.inst_name }}"
