---

galaxy_info:
  author: IBM
  description: Role to configure authentication policies
  company: IBM

  license: Apache

  min_ansible_version: "2.5"

  galaxy_tags:
    - v1.0.0
    - isam
    - ibm
    - set_file
    - access_control_policies

dependencies:
  - ibm.isam.common_handlers
