---

# Default variables for configuration of authentication mechanisms
authentication_mechanisms: []
# Default variables for filtering
mechanism_action: "{{ item.mechanism_action }}"
mechanism_name: "{{ item.name }}"
