---

# Default variables for configuration of runtime tuning parameters
runtime_tunings: []
# Default variables to filter for configuration of specific runtime tuning parameters at runtime
option: "{{ item.option }}"
runtime_action: "{{ item.runtime_action }}"
