# main task to upload signer certificates
#   Example:
#      upload_signer_certificates:
#         -   kdb_id: "{{ item.kdb_id }}"
#             cert: "{{ inventory_dir }}/{{ item.cert  }}"
#             label: "{{ item.label }}"
---
- name: Upload signer certificates
  ibm.isam.isam:
    log:       "{{ log_level | default(omit) }}"
    force:     "{{ force | default(omit) }}"
    action: ibmsecurity.isam.base.ssl_certificates.signer_certificate.import_cert
    isamapi:
      kdb_id: "{{ item.kdb_id }}"
      cert: "{{ inventory_dir }}/{{ item.cert  }}"
      label: "{{ item.label }}"
  with_items: "{{ upload_signer_certificates }}"
  notify: Commit Changes
