galaxy_info:
  author: IBM
  description: Role to set password for system accounts
  company: IBM

  license: Apache

  min_ansible_version: 2.2

  galaxy_tags:
  - isam
  - ibm
  - set_password
  - sysaccounts

dependencies:
  - common_handlers
