---
galaxy_info:
  author: IBM
  description: Retrieve mapping rule by name
  company: IBM

  license: Apache

  min_ansible_version: "2.7"

  platforms:
    - name: Fedora
      versions:
        - 30
        - 29
        - 28
        - 27
    - name: EL
      versions:
        - 8
        - 7
        - 6

  galaxy_tags:
    - isam
    - ibm
    - mappingrules
    - search

dependencies:
