- name: Compare Reverse Proxy->{{ reverseproxy.id }} Management Root Directories/Files
  ibm.isam.ibm.isam.isamcompare:
    appliance1: "{{ master_hostname }}"
    log:        "{{ log_level | default('INFO') }}"
    action: ibmsecurity.isam.web.reverse_proxy.management_root.directory
    isamapi:
      instance_id: "{{ reverseproxy.id }}"
  ignore_errors: true
  register: ret_obj

- name: Show Differences - values do not match!
  debug: msg="{{ ret_obj['data']['difference'].split('\n') }}"
  ignore_errors: true
  when: not ret_obj['data']['matches']

- name: Show Log - command failed!
  debug: msg="{{ ret_obj['log'].split('\n') }}"
  ignore_errors: true
  when: ret_obj|failed

- name: Compare Reverse Proxy->{{ reverseproxy.id }} Junctions
  ibm.isam.ibm.isam.isamcompare:
    appliance1: "{{ master_hostname }}"
    log:        "{{ log_level | default('INFO') }}"
    action: ibmsecurity.isam.web.reverse_proxy.junctions
    isamapi:
      reverseproxy_id: "{{ reverseproxy.id }}"
  ignore_errors: true
  register: ret_obj

- name: Show Differences - values do not match!
  debug: msg="{{ ret_obj['data']['difference'].split('\n') }}"
  ignore_errors: true
  when: not ret_obj['data']['matches']

- name: Show Log - command failed!
  debug: msg="{{ ret_obj['log'].split('\n') }}"
  ignore_errors: true
  when: ret_obj|failed

- name: Compare Reverse Proxy->{{ reverseproxy.id }} stanza/entries
  ibm.isam.ibm.isam.isamcompare:
    appliance1: "{{ master_hostname }}"
    log:        "{{ log_level | default('INFO') }}"
    action: ibmsecurity.isam.web.reverse_proxy.configuration.stanza
    isamapi:
      reverseproxy_id: "{{ reverseproxy.id }}"
  ignore_errors: true
  register: ret_obj

- name: Show Differences - values do not match!
  debug: msg="{{ ret_obj['data']['difference'].split('\n') }}"
  ignore_errors: true
  when: not ret_obj['data']['matches']

- name: Show Log - command failed!
  debug: msg="{{ ret_obj['log'].split('\n') }}"
  ignore_errors: true
  when: ret_obj|failed
