---
- name: Compare Reverse Proxy-> {{ reverseproxy.id }} Management Root Directories/Files
  ibm.isam.isamcompare:
    appliance1: "{{ inventory_hostname }}"
    appliance2: "{{ master_hostname }}"
    password1: "{{ ansible_isam_password }}"
    password2: "{{ master_password }}"
    log: "{{ log_level | default('INFO') }}"
    action: ibmsecurity.isam.web.reverse_proxy.management_root.directory
    isamapi:
      instance_id: "{{ reverseproxy.id }}"
  ignore_errors: true
  register: ret_obj

- name: Show Differences - values do not match!
  ansible.builtin.debug: msg="{{ ret_obj['data']['difference'].split('\n') }}"
  ignore_errors: true
  when:
    - ret_obj['data']['matches'] is defined
    - not ret_obj['data']['matches']

- name: Show Log - command failed!
  ansible.builtin.debug: msg="{{ ret_obj['log'].split('\n') }}"
  ignore_errors: true
  when: ret_obj['failed'] is true

- name: Compare Reverse Proxy->{{ reverseproxy.id }} Junctions
  ibm.isam.isamcompare:
    appliance1: "{{ inventory_hostname }}"
    appliance2: "{{ master_hostname }}"
    password1: "{{ ansible_isam_password }}"
    password2: "{{ master_password }}"
    log: "{{ log_level | default('INFO') }}"
    action: ibmsecurity.isam.web.reverse_proxy.junctions
    isamapi:
      reverseproxy_id: "{{ reverseproxy.id }}"
  ignore_errors: true
  register: ret_obj

- name: Show Differences - values do not match!
  ansible.builtin.debug: msg="{{ ret_obj['data']['difference'].split('\n') }}"
  ignore_errors: true
  when:
    - ret_obj['data']['matches'] is defined
    - not ret_obj['data']['matches']

- name: Show Log - command failed!
  ansible.builtin.debug: msg="{{ ret_obj['log'].split('\n') }}"
  ignore_errors: true
  when: ret_obj['failed'] is true

- name: Compare Reverse Proxy->{{ reverseproxy.id }} stanza/entries
  ibm.isam.isamcompare:
    appliance1: "{{ inventory_hostname }}"
    appliance2: "{{ master_hostname }}"
    password1: "{{ ansible_isam_password }}"
    password2: "{{ master_password }}"
    log: "{{ log_level | default('INFO') }}"
    action: ibmsecurity.isam.web.reverse_proxy.configuration.stanza
    isamapi:
      reverseproxy_id: "{{ reverseproxy.id }}"
  ignore_errors: true
  register: ret_obj

- name: Show Differences - values do not match!
  ansible.builtin.debug: msg="{{ ret_obj['data']['difference'].split('\n') }}"
  ignore_errors: true
  when:
    - ret_obj['data']['matches'] is defined
    - not ret_obj['data']['matches']

- name: Show Log - command failed!
  ansible.builtin.debug: msg="{{ ret_obj['log'].split('\n') }}"
  ignore_errors: true
  when: ret_obj['failed'] is true
