---
galaxy_info:
  author: IBM
  description: Role to create obligations
  company: IBM

  license: Apache

  min_ansible_version: "2.7"

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - isam
    - ibm
    - create
    - authentication
    - obligation

dependencies:
  - ibm.isam.common_handlers
