- name: Search for a Mapping Rule
  ibm.isam.isam:
    log:       "{{ log_level | default('INFO') }}"
    force:     "{{ force | default(False) }}"
    action: ibmsecurity.isam.aac.mapping_rules.search
    isamapi:
      name: "{{ search_mapping_rule_name }}"
  when: search_mapping_rule_name is defined
  register: ret_obj
