---

galaxy_info:
  author: IBM
  description: Role to configure static routes
  company: IBM

  license: Apache

  min_ansible_version: '2.2'

  galaxy_tags:
  - isam
  - ibm
  - configure
  - static_routes

dependencies:
  - ibm.isam.common_handlers
