---
galaxy_info:
  author: IBM
  description: Role to configure addresses for multiple interfaces
  company: IBM

  license: Apache

  min_ansible_version: 2.5

  galaxy_tags:
  - isam
  - ibm
  - configure
  - networking

dependencies:
  - ibm.isam.common_handlers
