---
# Use Default domain, override as needed
admin_domain: Default

# Initialize pdadmin_commands
pdadmin_commands: []

# Disable merging action plugin by default (https://pypi.org/project/ansible-merge-vars)
#  needs extra python package: pip install ansible-merge-vars
enable_ansible_merge_vars: false
