---
set_cluster_config_comment: Execute snapshot before configuring cluster

set_cluster_config_primary_master: 127.0.0.1
set_cluster_config_secondary_master:
set_cluster_config_master_ere:
set_cluster_config_tertiary_master:
set_cluster_config_quaternary_master:
set_cluster_config_dsc_external_clients: false
set_cluster_config_dsc_port:
set_cluster_config_dsc_use_ssl:
set_cluster_config_dsc_ssl_label:
set_cluster_config_dsc_worker_threads: 64
set_cluster_config_dsc_maximum_session_lifetime: 3600
set_cluster_config_dsc_client_grace_period: 600
set_cluster_config_hvdb_embedded: true
set_cluster_config_hvdb_max_size: 40
set_cluster_config_hvdb_db_type:
set_cluster_config_hvdb_address:
set_cluster_config_hvdb_port:
set_cluster_config_hvdb_user:
set_cluster_config_hvdb_db2_alt_address:
set_cluster_config_hvdb_db2_alt_port:
set_cluster_config_hvdb_db_name:
set_cluster_config_hvdb_db_secure:
set_cluster_config_hvdb_driver_type:
set_cluster_config_hvdb_solid_tc:
set_cluster_config_cfgdb_embedded: true
set_cluster_config_cfgdb_db_type:
set_cluster_config_cfgdb_address:
set_cluster_config_cfgdb_port:
set_cluster_config_cfgdb_user:
set_cluster_config_cfgdb_db2_alt_address:
set_cluster_config_cfgdb_db2_alt_port:
set_cluster_config_cfgdb_db_name:
set_cluster_config_cfgdb_db_secure:
set_cluster_config_cfgdb_driver_type:
set_cluster_config_cfgdb_solid_tc:
set_cluster_config_first_port: 2020
set_cluster_config_cfgdb_fs:
set_cluster_config_dsc_trace_level:
