---
# tasks file for export_metadata

- name: Export a federation
  ibm.isam.isam:
    log:       "{{ log_level | default(omit) }}"
    force:     "{{ force | default(omit) }}"
    action: ibmsecurity.isam.fed.federations.export_metadata
    isamapi:
      name: "{{ export_metadata_name }}"
      filename: "{{ export_metadata_filename }}"