galaxy_info:
  author: IBM
  description: Role to publish snapshot from configuration container [docker]
  company: IBM

  license: Apache

  min_ansible_version: 2.2

  galaxy_tags:
  - isam
  - ibm
  - publish
  - docker

dependencies:
  - ibm.isam.common_handlers
