---

galaxy_info:
  author: IBM
  description: Role to configure system accounts
  company: IBM

  license: Apache

  min_ansible_version: "2.2"

  galaxy_tags:
    - isam
    - ibm
    - configure
    - sysaccounts

dependencies:
  - ibm.isam.common_handlers
