---
galaxy_info:
  author: IBM
  description: Role to delete single reverse proxy instance
  company: IBM

  license: Apache

  min_ansible_version: "2.2"

  galaxy_tags:
    - isam
    - ibm
    - delete
    - reverseproxy

dependencies:
  - ibm.isam.common_handlers
