galaxy_info:
  author: IBM
  description: Role to configure reverse proxy junctions in 1 go
  company: IBM

  license: Apache

  min_ansible_version: 2.9

  galaxy_tags:
  - isam
  - ibm
  - configure
  - reverse_proxy_junctions

dependencies:
  - ibm.isam.common_handlers
