---
galaxy_info:
  author: IBM
  description: Role to auto-configure reverse proxy for oauth
  company: IBM

  license: Apache

  min_ansible_version: "2.2"

  galaxy_tags:
    - isam
    - ibm
    - configure
    - reverse_proxy_oauth

dependencies:
  - ibm.isam.common_handlers
